# Generated by Django 4.2.10 on 2025-03-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='last_code_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
