# Generated by Django 4.2.10 on 2025-03-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_integration', '0002_telegramaccount_last_code_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='sender_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
