# Generated by Django 4.2.10 on 2025-03-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_integration', '0003_telegrammessage_sender_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('VOICE', 'Voice Message'), ('DOCUMENT', 'Document'), ('PHOTO', 'Photo'), ('OTHER', 'Unsupported Type')], default='TEXT', max_length=10),
        ),
    ]
